apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}-cm
  {{- include "mychart.labels" . | nindent 4 }}
data:
  application.properties: |-
    {{ .Files.Get .Values.configMap.properties | indent 8 }}
