apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.clusterIPPort }}
    targetPort: {{ .Values.image.containerPort }}
  selector:
    app: {{ .Values.deployment.name }}