environment: DEV
deployment:
  name: <REPO_NAME>
  replicaCount: 1
image:
  account: nginx
  tag: latest
  containerPort: 8080
service:
  type: ClusterIP
  clusterIPPort: 8080
  ingress:
    enables: false
    hostname: test.example.com
resource:
  cpu:
    requests: 0.1
    limit: 0.5
  memory:
    requests: 250Mi
    limit: 500Mi
configMap:
  properties: files/dev/application.properties
probes:
  liveness:
    enabled: true
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /ready
      port: http
    periodSeconds: 10
  startup:
    enabled: false
    httpGet:
      path: /startup
      port: http
    failureThreshold: 30
    periodSeconds: 10

